### ISSUE TITLE
Support api-v3

### ISSUE THREAD

**Issue by megoRU** [boticord/boticordjava#10]
- [x] Боты
- [x] Профили
- [x] Поиск по сайту
- [x] Сервера
- [x] WS

**Comment by everydayrains** [comment]
@megoRU есть прогресс? На котлине уже сделали для в3 boticord/docs-v3#14

**Comment by megoRU** [comment]
На котлине сделали велосипед. Будет нормальное API сделаю.

**Comment by everydayrains** [comment]
А оно ненормальное сейчас?)

**Comment by megoRU** [comment]
Когда я делал по v3 там еще что-то было не написано. Как сейчас не знаю. Но к 15 числу постараюсь сделать

**Comment by everydayrains** [comment]
Все было там написано, доки еще зимой были готовы но никто их не афишировал

**Comment by MagM1go** [comment]
> На котлине сделали велосипед. Будет нормальное API сделаю. Смысл 2 либы под 1 JVM язык 🤦‍♀

что конкретно велосипед

**Comment by megoRU** [comment]
> > На котлине сделали велосипед. Будет нормальное API сделаю. Смысл 2 либы под 1 JVM язык 🤦‍♀
> 
> что конкретно велосипед

Всё что нужно знать о качественном OpenSource
![image](https://github.com/boticord/boticordjava/assets/23276305/a03b4bd2-9964-4158-9d4e-cd9dd016e19f)

**Comment by MagM1go** [comment]
> > > На котлине сделали велосипед. Будет нормальное API сделаю. Смысл 2 либы под 1 JVM язык 🤦‍♀
> > 
> > 
> > что конкретно велосипед
> 
> Всё что нужно знать о качественном OpenSource ![image](https://user-images.githubusercontent.com/23276305/244862357-a03b4bd2-9964-4158-9d4e-cd9dd016e19f.png)

Ну раз ты про рофельные коммиты, то тут соглашусь, но там никаких полезных приколов особо и не было, да и либой ещё никто не пользуется, не думаю, что тут прям жесть как важно было соблюдать что-то. Но вопрос был про велосипед, а не про то, как я вёл гитхаб либы

**Comment by megoRU** [comment]
> @megoRU есть прогресс? На котлине уже сделали для в3 [boticord/docs-v3#14](https://github.com/boticord/docs-v3/pull/14)

Осталось: 
1. поиск по ботам
2. поиск по комментариям
3. WS
4. Навести общий марафет

**Comment by Mirdukkk** [comment]
короткие ссылки были перенесены в настройки пермиальных ресурсов, поэтому CRUD под них должен быть удалён. больше нельзя программно их обновлять, удалять и т.д.

**Comment by megoRU** [comment]
Closed https://github.com/boticord/boticordjava/commit/3a0c4655b07595f1095ae0a3668dd7041dd23bf6
